batch_size: 4
cache_dir: ./cache/pri30k
col_binding_site: Binding site renumbered merged
col_ligand: Binding ligands
col_na_chain: RNA chains
col_prot_chain: Protein chains
col_prot_name: PDB
data_root: ./datasets/PRI30k/PDBs
dataset_type: pri30k_dataset
df_path: tmp/pri30k_filtered.csv
loss_type: regression
num_workers: 0
pin_memory: true
strategy: separate
transform:
- resolution: backbone
  type: select_atom
- patch_size: 256
  type: selected_region_with_distmap
- type: subtract_center_of_mass
